# NUMPY 

# Neden NumPy Kullanılır?

NumPy, Python dilinde sayısal işlemler yapmak için sıkça kullanılan güçlü bir kütüphanedir. Özellikle **matematiksel** ve **istatistiksel** hesaplamalarda büyük kolaylık sağlar.

---

## NumPy'nin Temel Avantajları

### 1. Hızlı Çalışma

NumPy dizilerinde tüm veriler **aynı türde** (homojen) tutulur. Bu sayede bellek daha verimli kullanılır ve işlemler, Python listelerine göre çok daha hızlı gerçekleşir.

> Örnek:  
> Python listesi farklı veri türleri içerebilirken, NumPy dizisi yalnızca tek bir türde veri tutar. Bu da veri işleme hızını artırır.

---

### 2. Vektörel İşlemler

NumPy, diziler üzerinde **toplu işlemler** yapılmasına olanak tanır. Döngü kullanmadan, tek satırlık komutlarla tüm dizi üzerinde işlem yapılabilir.

> Bu sayede:
> - Daha az kod yazılır.
> - İşlemler daha kısa sürede tamamlanır.
> - Kod daha okunabilir ve düzenli olur.

---

NumPy bu iki temel özelliğiyle bilimsel projelerde, veri analizi ve makine öğrenmesi gibi alanlarda sıkça tercih edilir.


In [ ]:
import numpy as np
a = [55,34,23,34]
b = [34,34,55,55]

ab=[] 

for i in range(0,len(a)):
    ab.append(a[i]*b[i])


print(ab)

# şimdi bunu bide numpy kullanarak array ile yapalım

c = np.array([55,34,23,34])
d = np.array([34,34,55,55])
c*d

# Bu örnekle liste oluşturmadık döngü kurmadık çok kolay şekilde numpy sayesinde hemen halletik

# NumPy Array'i Oluşturma (Creating NumPy Arrays)

NumPy array'leri, Python'daki diğer veri yapıları gibi kullanılan özel bir yapıdır. Python'da sıkça kullanılan veri yapıları şunlardır:

- `int` (tam sayılar)
- `float` (ondalıklı sayılar)
- `str` (metinler)
- `list` (listeler)
- `dict` (sözlükler)
- `tuple` (demetler)
- `set` (kümeler)

NumPy kütüphanesinin temel veri yapısı ise **NumPy array**'idir (dizi yapısı). NumPy ile çalışabilmek için öncelikle bu array yapısını oluşturmamız gerekir.

Array’ler sayesinde veriler üzerinde matematiksel ve istatistiksel işlemler daha kolay ve hızlı bir şekilde yapılabilir.

> Kısacası:  
> NumPy'da işlem yapmanın ilk adımı, verileri bir **array** (dizi) haline getirmektir.



In [ ]:
a = np.array([5,6,7,8,9])
type(a) 

In [ ]:
np.zeros(10,dtype=int) # zeros sıfır üretir dtype ise type söyler 

In [ ]:
np.random.randint(0,7, size = 7)

In [ ]:
np.random.normal(15,5,(3,3))
# Ortalaması 15 standart sapması 5 olan  3x3  olan Normal Dağılımlı sayılar oluşturdu

# NumPy Array Özellikleri

NumPy array'leri, yapıları hakkında bilgi veren bazı önemli özelliklere sahiptir:

- **`ndim`** → Array’in kaç boyutlu olduğunu gösterir.  
Buradaki "boyut", verinin kaç seviyeli yapıda olduğunu ifade eder.

    Tek boyutlu array (`ndim = 1`)**  
    Düz bir liste gibidir.  
    Örnek: `[1, 2, 3, 4]` → 1D array (tek satır gibi düşünebilirsin)

    İki boyutlu array (`ndim = 2`)**  
    Satır ve sütunlardan oluşur, bir tabloya benzer.  
    Örnek: `[[1, 2], [3, 4]]` → 2D array (2 satır, 2 sütun)

- **`shape`** → Array’in her boyuttaki eleman sayısını verir.  
  *Örneğin, 3 satır 4 sütundan oluşan bir array’in şekli `(3, 4)` olur.*

- **`size`** → Array’deki toplam eleman sayısını verir.  
  *Örneğin, `(3, 4)` şekline sahip bir array için `size = 12` olur.*

- **`dtype`** → Array’deki elemanların veri tipini gösterir.  
  *Örneğin, tamsayı elemanlar için `dtype=int64`, ondalıklı elemanlar için `dtype=float64` olabilir.*


In [ ]:
a = np.random.randint(10,20, size=9)
# 10 ile 20 arasında rastgele 9 sayı verecektir bize 
a

In [ ]:
a.ndim 
# Boyut sayısı veriyor 1

In [ ]:
a.shape
# Boyut bilgisini veriyor tek boyutlu 9 elemanlı

In [ ]:
a.size
# Toplam eleman sayısı

In [ ]:
a.dtype

# Yeniden Şekillendirme (Reshaping)

Elimizdeki bir NumPy array’inin boyutunu (şeklini) değiştirmek için **`reshape()`** fonksiyonu kullanılır.

Bu işlem, verinin içeriğini değiştirmez; sadece veri yapısını, yani boyutlarını değiştirir.

---

## Önemli Nokta:

`reshape()` işlemini yaparken, toplam eleman sayısının (`size`) uyumlu olması gerekir.

> Örnek:  
> Elimizde 5 elemanlı bir array varsa, bunu `3x3` şeklinde bir yapıya **dönüştüremeyiz**, çünkü 3×3 = 9 eleman gerekir.  
> Bu durumda **hata alınır**.

In [ ]:
a.reshape(3,3)

In [ ]:
np.random.randint(10,20, size=9)
np.random.randint(10,20, size=9).reshape(3,3)

# ⭐ INDEX SEÇİMİ (Indexing)

Veri yapılarında, belirli bir veriye ulaşmak için **indeks seçimi (indexing)** kullanılır.  
NumPy array’lerinde de istediğimiz elemanı ya da alt diziyi seçmek için index kullanırız.

---

## Temel Bilgi:

NumPy'da indeksler **0'dan başlar**.  
Yani ilk eleman `0`, ikinci eleman `1` şeklinde numaralandırılır.

In [ ]:
indexa = a[0] # Bize 1.elemanı götürür 
indexa

In [ ]:
indexb = a[0:5] # 0 dan 5 E KADAR 5 dahil değildir 
indexb

In [ ]:
a[0] = 1881  # yaptığımız da elemanı değiştirebiliriz
a

In [ ]:
# 2 Boyutlu array olursa nasıl seçiyoruz onu yapalım
a2 = np.random.randint(40,size=(3,4)) # 3 satır 5 sütunlu bir array oluştur
a2

In [ ]:
# Burada ilk satırı sonra virgül ekledikten sonra sütunu belirlememiz lazım 
a2[0,1]

In [ ]:
a2[0,1] = 666
a2

# ⚠️ DİKKAT: NumPy'da Veri Türü Sabittir (Fixed Type)

NumPy array'lerinde **veri türü (data type)** sabittir.  
Yani bir array oluşturulduğunda, tüm elemanlar **aynı veri türünde** saklanır.
> NumPy der ki:  
> "Ben tüm verileri **tek bir veri türünde** saklarım. Bu sayede hem **daha az bellek** kullanırım hem de **daha hızlı** çalışırım."


In [ ]:

a2[0,1] = 2.4
a2


In [ ]:
a2[:,0] # :, kısmı tüm her şeyi seç 0 ise 0.sütunu seçmesini belirt

In [ ]:
a2[1,:] # satırı seçmemizi söğlar

In [ ]:
a2[0:1,0:2] # Satırlarda 0 dan 1 E KADAR sütunlarda 0 dan 2 E KADAR git demek

# Fancy Indexing (Gelişmiş İndeksleme)

**Fancy indexing**, bir NumPy array’indeki birden fazla elemana, **index numaralarını liste veya array olarak vererek** kolayca erişmemizi sağlar.

Normal indexlemeden farklı olarak, tek tek değil, **birden fazla elemanı aynı anda** seçmemize olanak tanır.

---

In [ ]:
v = np.arange(0,30,3) # 0 dan 30 a kadar 3 er 3 er array oluştur

In [ ]:
v[3] 

In [ ]:
catch =[5,6,7]  
v[catch] #bize 5 6 7 indexdeki elemanları seçti

# Numpy'da koşullu işlemler(Conditions on numpy)


In [35]:
import numpy as np

v2 = np.array([99, 34, 55, 23]) # Yukarıda bir kere daha liste yaptığımız için hata veriyor kernel restartla
gg = []

for i in v2:
    if i < 60:
        gg.append(i)

print(gg)


[34, 55, 23]


In [7]:
# NumPy ile yapalım
# Bir array ın içinden koşullu eleman seçerken şöyle yapıyoruz
print(v2 < 50)  
print(v2[v2<50]) # 50 den küçükler gelsin
print(v2[v2>50]) # 50 den büyükler gelsin
print(v2[v2!=50]) # 50 den farklı olanlar gelsin
print(v2[v2==50]) # 50 ye eşit olanlar gelsin
print(v2[v2>=50]) # 50 dahil büyükler gelsin


[False  True False  True]
[34 23]
[99 55]
[99 34 55 23]
[]
[99 55]


# Matematiksel İşlemler


In [14]:
print(v2 / 5)
print(v2*5/10)
print(v2 ** 2)
print(v2 - 15)

[19.8  6.8 11.   4.6]
[49.5 17.  27.5 11.5]
[9801 1156 3025  529]
[84 19 40  8]


In [17]:
np.subtract(v2,4) # Çıkartma işlemi

array([95, 30, 51, 19])

In [ ]:
np.add(v2,4) # Toplama işlemi

array([103,  38,  59,  27])

In [19]:
np.mean(v2) # Ortalama işlemi

52.75

In [ ]:
np.sum(v2) # Toplam işlemi

211

In [21]:
np.min(v2) # min değeri

23

In [ ]:
np.max(v2) # max değeri

99

In [ ]:
np.var(v2) # Varyansı verir

845.1875

In [26]:
np.median(v2) # Medyan değeri

44.5

In [ ]:
np.std(v2) # Standart sapmasını verir

29.07210862665452

In [36]:
# NOT: Eğer arrayda yaptığımız değişiklik örneğin +1 yaptık tüm değelere bunu kalıcı
# olmasını istiyorsak atama yapmayı unutmamalıyız
v2 = np.add(v2,1)
v2

array([100,  35,  56,  24])

In [34]:
# eski haline getirelim
v2 = np.subtract(v2,1)
v2

array([99, 34, 55, 23])

In [37]:
# İki bilinmeyenli bir denklem çözmek istersek
# 6x0 + 2x1 = 12
# x0  + 7x1 = 87
a = np.array([[5,1],[1,3]])
b = np.array([12,10])

np.linalg.solve(a,b)

array([1.85714286, 2.71428571])

# NumPy Genel Özeti 📌

**NumPy**, Python’da **sayısal verilerle çalışmak** için geliştirilmiş güçlü bir kütüphanedir.  
Özellikle veri analizi, bilimsel hesaplamalar ve makine öğrenmesi gibi alanlarda yaygın olarak kullanılır.

---

## ✅ Neden NumPy Kullanılır?

- **Hızlıdır:** Sabit veri tipi (fixed type) kullanır, belleği verimli kullanır.
- **Verimli çalışır:** Vektörel işlemlerle döngü kullanmadan çok sayıda işlem yapılabilir.
- **Kolaydır:** Matris ve dizi işlemleri sade sözdizimiyle kolaylaştırılmıştır.
- **Güçlüdür:** Çok boyutlu dizilerle (1D, 2D, 3D...) rahatça çalışılır.

---

## 🧩 NumPy'nin Temel Yapısı: Array

- NumPy'da veriler **array** (dizi) yapısında tutulur.
- Tek boyutlu (`1D`), çift boyutlu (`2D`) veya daha fazla boyutlu diziler oluşturulabilir.
- Listeye benzer ama çok daha hızlı ve işlevseldir.

---

## 🔢 Nümerik ve İstatistiksel İşlemler

NumPy ile şunlar kolayca yapılabilir:

- **Ortalama, medyan, varyans, standart sapma**  
  `mean()`, `median()`, `var()`, `std()`

- **Toplam, çarpım, min–max, yüzde dilim**  
  `sum()`, `prod()`, `min()`, `max()`, `percentile()`, `quantile()`

- **Matematiksel fonksiyonlar**  
  `sin()`, `cos()`, `log()`, `sqrt()`, `exp()`, vs.

---

## 🔍 Veri Seçimi ve Şekillendirme

- **Indexing ve slicing**: Dizi elemanlarına ulaşmak için.
- **Fancy indexing & boolean indexing**: Koşullu veya özel index ile seçim.
- **reshape()**: Dizinin şeklini değiştirme.
- **flatten()**: Çok boyutlu diziyi tek boyuta indirme.

---

## 📌 Kısaca NumPy:

> - Bilimsel hesaplama için temel araçtır.  
> - Hızlı, verimli ve esnek veri işlemleri sağlar.  
> - Veri analizi ve makine öğrenmesinde sıkça kullanılır.  

**NumPy bilmek, Python ile veriyle çalışmanın temelidir.**
